// packages/web/src/components/shared/AuthorCard.vue
<script setup lang="ts">
import type { Author } from '@loikmon/api'
defineProps<{ author: Author }>()
</script>

<template>
  <RouterLink :to="`/authors/${author.id}`" class="group block">
    <div class="card p-4 text-center">
      <div class="w-16 h-16 rounded-full overflow-hidden bg-brand-100 dark:bg-brand-900/30 mx-auto mb-3 flex items-center justify-center">
        <img v-if="author.avatar_url ?? author.avatar" :src="author.avatar_url ?? author.avatar" :alt="author.name" class="w-full h-full object-cover" />
        <span v-else class="text-2xl text-brand-600 dark:text-brand-400 font-bold">{{ author.name.charAt(0) }}</span>
      </div>
      <h3 class="text-sm font-semibold text-gray-900 dark:text-white group-hover:text-brand-600 dark:group-hover:text-brand-400 transition-colors truncate">
        {{ author.name }}
      </h3>
      <p class="text-xs text-gray-400 mt-0.5">{{ author.books_count ?? 0 }} books</p>
    </div>
  </RouterLink>
</template>

// packages/mobile/src/components/AuthorCard.tsx
import { View, Text, Image, Pressable } from 'react-native'
import { Link } from 'expo-router'
import type { Author } from '@loikmon/api'
import { fixUrl } from '@/lib/url'

export function AuthorCard({ author }: { author: Author }) {
  const avatar = fixUrl((author.avatar_url as string) ?? (author.avatar as string) ?? '')
  return (
    <Link href={`/author/${author.id}`} asChild>
      <Pressable className="mb-3 flex-row items-center rounded-xl bg-white dark:bg-surface-800 p-3">
        <View className="h-14 w-14 overflow-hidden rounded-full bg-surface-200 dark:bg-surface-700">
          {avatar ? (
            <Image source={{ uri: avatar }} className="h-full w-full" resizeMode="cover" />
          ) : (
            <View className="h-full w-full items-center justify-center">
              <Text className="text-xl">👤</Text>
            </View>
          )}
        </View>
        <View className="ml-3 flex-1">
          <Text className="text-sm font-semibold text-surface-900 dark:text-surface-50">
            {author.name}
          </Text>
          {author.bio ? (
            <Text numberOfLines={1} className="text-xs text-surface-400">
              {author.bio}
            </Text>
          ) : null}
        </View>
      </Pressable>
    </Link>
  )
}
