// packages/web/src/components/shared/EmptyState.vue
<script setup lang="ts">
defineProps<{ icon?: string; title: string; description?: string }>()
</script>

<template>
  <div class="flex flex-col items-center justify-center py-16 text-center px-4">
    <div class="text-5xl mb-4">{{ icon ?? '📭' }}</div>
    <h3 class="text-lg font-semibold text-gray-700 dark:text-gray-300">{{ title }}</h3>
    <p v-if="description" class="mt-1 text-sm text-gray-400 max-w-xs">{{ description }}</p>
    <slot />
  </div>
</template>

// packages/mobile/src/components/EmptyState.tsx
import { View, Text } from 'react-native'

export function EmptyState({
  icon = '📭',
  title,
  subtitle,
}: {
  icon?: string
  title: string
  subtitle?: string
}) {
  return (
    <View className="flex-1 items-center justify-center px-8 py-16">
      <Text className="text-5xl mb-3">{icon}</Text>
      <Text className="text-base font-semibold text-surface-800 dark:text-surface-100 text-center">
        {title}
      </Text>
      {subtitle ? (
        <Text className="mt-1 text-sm text-surface-500 dark:text-surface-400 text-center">
          {subtitle}
        </Text>
      ) : null}
    </View>
  )
}
